apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ${{values.name}}

resources:
  - rollout.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: IMAGE_PLACEHOLDER
    newName: 351619759866.dkr.ecr.us-west-2.amazonaws.com/${{values.owner | replace("group:", "") | replace("team-", "")}}/${{values.name}}
    newTag: latest

commonLabels:
  app.kubernetes.io/name: ${{values.name}}
  app.kubernetes.io/component: frontend
  fasti.sh/team: ${{values.owner | replace("group:", "") | replace("team-", "")}}
